apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: board-frontend-ingress
  namespace: board-app
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - moodie.shop
      secretName: board-frontend-tls
  rules:
    - host: moodie.shop
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: board-frontend-service
                port:
                  number: 80
