apiVersion: v1
kind: Service
metadata:
  name: board-frontend-service
  namespace: board-app
spec:
  type: ClusterIP
  selector:
    app: board-frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
